### PR TITLE
refactor: mails

### PR DESCRIPTION
**Pull request by mrdrozdy**
Delicious and easy to prepare bigos made of sauerkraut with pork, sausage, dried mushrooms.

Preparation

Dice the meat. Dice the onion and fry in oil in a large pot. Add the meat and fry it thoroughly.
Pour in 2 cups of hot broth or water with salt and pepper, bring to a boil. Then add the broken dried mushrooms, cover, reduce the heat and cook for about 45 minutes.
Add bay leaf, allspice, cumin, marjoram, plum jam or chopped plums, peeled and diced peeled apple and mix.
Add the squeezed sauerkraut and pour in a glass of water, mix. Cover and cook for about 15 minutes.
Peel the sausage, cut into cubes and fry in a pan. Add to cabbage and cook for about 30 minutes. Add tomato paste at the end.
Fry flour in a dry pan, when it starts to brown add a tablespoon of butter and stir until the butter melts.
Keeping the pan on the heat add a few tablespoons of cabbage gradually stirring all the time. Transfer the contents of the pan back to the pot, mix and bring to the boil.

### CODE REVIEW

**Comment by atakowiec** [comment]
thanks, it works on my machine!
image

**Review by atakowiec — APPROVED** [review]
image

**Comment by weronika28** [comment]
approve

**Comment by atakowiec** [comment]
> approve

image

**Comment by mrdrozdy** [comment]
b826fdfc42eff440ecf7983b05b0aac2

**Pull request merged**
